// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbbE6YzXEEYkCZxJGEKmt6Pqak8U7Pdrw',
    appId: '1:953750763068:web:fcc0dc6d46008653eab539',
    messagingSenderId: '953750763068',
    projectId: 'firenotee',
    authDomain: 'firenotee.firebaseapp.com',
    storageBucket: 'firenotee.firebasestorage.app',
    measurementId: 'G-3Z9T5WYDGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6hxy41VGpoPBk6gF7R0kwy6ShigwvHk',
    appId: '1:953750763068:android:09b6f516c367ed4feab539',
    messagingSenderId: '953750763068',
    projectId: 'firenotee',
    storageBucket: 'firenotee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgD_sRCe-aEkAKUU11KnVSqssMyxGQno',
    appId: '1:953750763068:ios:8b781abad42c716aeab539',
    messagingSenderId: '953750763068',
    projectId: 'firenotee',
    storageBucket: 'firenotee.firebasestorage.app',
    iosBundleId: 'com.example.fireNotee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgD_sRCe-aEkAKUU11KnVSqssMyxGQno',
    appId: '1:953750763068:ios:8b781abad42c716aeab539',
    messagingSenderId: '953750763068',
    projectId: 'firenotee',
    storageBucket: 'firenotee.firebasestorage.app',
    iosBundleId: 'com.example.fireNotee',
  );
}
